USE DATA1;
CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    COUNTRY VARCHAR(100)
);
DESC CUSTOMER;
CREATE TABLE ORDERS(
    ORDER_ID INT,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    TOTAL_AMOUNT DECIMAL
);
DESC ORDERS;
CREATE TABLE ORDER_ITEMS(
    ORDER_ITEM_ID INT,
    ORDER_ID INT,
    PRODUCT_ID INT,
    QUALITY INT,
    PRICE DECIMAL
);
DESC ORDER_ITEMS;
CREATE TABLE PRODUCTS(
    PRODUCT_ID INT,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100)
);
DESC PRODUCTS;
SELECT 
    CUSTOMER.CUSTOMER_NAME,
    CUSTOMER.COUNTRY,
    SUM(ORDERS.TOTAL_AMOUNT) AS 'TOTAL SPEND'
FROM
    CUSTOMER
        JOIN
    ORDERS ON CUSTOMER.CUSTOMER_ID = ORDERS.CUSTOMER_ID
GROUP BY CUSTOMER.CUSTOMER_NAME , CUSTOMER.COUNTRY;
SELECT 
    CUSTOMER.CUSTOMER_NAME,
    CUSTOMER.COUNTRY,
    SUM(ORDERS.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM
    CUSTOMER
        JOIN
    ORDERS ON CUSTOMER.CUSTOMER_ID = ORDERS.CUSTOMER_ID
GROUP BY CUSTOMER.CUSTOMER_NAME , CUSTOMER.COUNTRY
ORDER BY TOTAL_SPENT DESC
LIMIT 5;


